# Generated by Django 3.2.5 on 2021-07-21 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='d_o_b',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, null=True, upload_to='project_photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
