# Generated by Django 3.2.5 on 2021-07-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
